fixed ipv6 filter bugs

diff --git a/pve-firewall b/pve-firewall
--- a/pve-firewall
+++ b/pve-firewall
@@ -288,7 +288,7 @@ function APPLY_VM_COMMON_RULES {
 
     # New connections (TCP, UDP, ICMP, ...) go to COMMON_VM_CHAIN
     $IPTABLES --table filter --append FORWARD -m conntrack --ctstate NEW --jump $VM_CHAIN
-    $IP6TABLES --table filter --append FORWARD -m conntrack --ctstate NEW --jump $VM_CHAIN
+    $IP6TABLES --table filter --append FORWARD --jump $VM_CHAIN
 
     # Call common bridged vm rules
     source $CONF_DIR/$COMMON_BRIDGED_CONF_FILENAME
@@ -776,107 +776,104 @@ function COMMON_BRIDGED_VM_PROTECTED_PORT {
 # Init firewall
 function INIT_FW {
 
-	# Enable IPTables for bridge
-	if [ -f $SYSCTL_PVE_CONF_FILE ]; then
-		# Change sysctl values
-		echo 'net.bridge.bridge-nf-call-ip6tables = 1' > $SYSCTL_PVE_CONF_FILE
-		echo 'net.bridge.bridge-nf-call-iptables = 1' >> $SYSCTL_PVE_CONF_FILE
-		echo 'net.bridge.bridge-nf-call-arptables = 0' >> $SYSCTL_PVE_CONF_FILE
-		echo 'net.bridge.bridge-nf-filter-vlan-tagged = 0' >> $SYSCTL_PVE_CONF_FILE
+    # Enable IPTables for bridge
+    if [ -f $SYSCTL_PVE_CONF_FILE ]; then
+	# Change sysctl values
+	echo 'net.bridge.bridge-nf-call-ip6tables = 1' > $SYSCTL_PVE_CONF_FILE
+	echo 'net.bridge.bridge-nf-call-iptables = 1' >> $SYSCTL_PVE_CONF_FILE
+	echo 'net.bridge.bridge-nf-call-arptables = 0' >> $SYSCTL_PVE_CONF_FILE
+	echo 'net.bridge.bridge-nf-filter-vlan-tagged = 0' >> $SYSCTL_PVE_CONF_FILE
 
-		# silently reload sysctl values
-		sysctl -p;
-		/etc/init.d/procps restart &> /dev/null
-	else
-		ERR_MSG "FATAL: Cannot find $SYSCTL_PVE_CONF_FILE file !"
-		exit 1;
-	fi
+	# silently reload sysctl values
+	sysctl -p;
+	/etc/init.d/procps restart &> /dev/null
+     else
+	ERR_MSG "FATAL: Cannot find $SYSCTL_PVE_CONF_FILE file !"
+	exit 1;
+     fi
 
-	# Create user chains
-	$IPTABLES --table filter --new-chain $PROXMOX_CHAIN
-	$IPTABLES --table filter --new-chain $COMMON_VM_CHAIN
-	$IPTABLES --table filter --new-chain $VM_CHAIN
-	$IPTABLES --table filter --new-chain $LOGDROP_CHAIN
+    # Create user chains
+    $IPTABLES --table filter --new-chain $PROXMOX_CHAIN
+    $IPTABLES --table filter --new-chain $COMMON_VM_CHAIN
+    $IPTABLES --table filter --new-chain $VM_CHAIN
+    $IPTABLES --table filter --new-chain $LOGDROP_CHAIN
 
-	$IP6TABLES --table filter --new-chain $PROXMOX_CHAIN
-	$IP6TABLES --table filter --new-chain $COMMON_VM_CHAIN
-	$IP6TABLES --table filter --new-chain $VM_CHAIN
-	$IP6TABLES --table filter --new-chain $LOGDROP_CHAIN
+    $IP6TABLES --table filter --new-chain $PROXMOX_CHAIN
+    $IP6TABLES --table filter --new-chain $COMMON_VM_CHAIN
+    $IP6TABLES --table filter --new-chain $VM_CHAIN
+    $IP6TABLES --table filter --new-chain $LOGDROP_CHAIN
 
 
-	# Init LOG_DROP user chain
-	if [ "$LOG_INVALID_PACKETS" -eq "1" ]; then
-		$IPTABLES --table filter --append $LOGDROP_CHAIN --jump LOG --log-prefix 'IPTABLES: ' --log-level info;
-		$IP6TABLES --table filter --append $LOGDROP_CHAIN --jump LOG --log-prefix 'IP6TABLES: ' --log-level info;
-	fi
+    # Init LOG_DROP user chain
+    if [ "$LOG_INVALID_PACKETS" -eq "1" ]; then
+	$IPTABLES --table filter --append $LOGDROP_CHAIN --jump LOG --log-prefix 'IPTABLES: ' --log-level info;
+	$IP6TABLES --table filter --append $LOGDROP_CHAIN --jump LOG --log-prefix 'IP6TABLES: ' --log-level info;
+    fi
 
-	$IPTABLES --table filter --append $LOGDROP_CHAIN --jump DROP
-	$IP6TABLES --table filter --append $LOGDROP_CHAIN --jump DROP
+    $IPTABLES --table filter --append $LOGDROP_CHAIN --jump DROP
+    $IP6TABLES --table filter --append $LOGDROP_CHAIN --jump DROP
 
-	# Inspect common guest rules after specific guest rules.
-	# This permits to overide rules for each guest before default decisions are applied
-	$IPTABLES --table filter --append $VM_CHAIN --jump $COMMON_VM_CHAIN
-	$IP6TABLES --table filter --append $VM_CHAIN --jump $COMMON_VM_CHAIN
+    # Inspect common guest rules after specific guest rules.
+    # This permits to overide rules for each guest before default decisions are applied
+    $IPTABLES --table filter --append $VM_CHAIN --jump $COMMON_VM_CHAIN
+    $IP6TABLES --table filter --append $VM_CHAIN --jump $COMMON_VM_CHAIN
 
-	# Enable ip_forward if required
-	if [ "$IP_FORWARD" -eq "1" ]; then
-		echo 1 > /proc/sys/net/ipv4/ip_forward &> /dev/null;
-	fi
+    # Enable ip_forward if required
+    if [ "$IP_FORWARD" -eq "1" ]; then
+	echo 1 > /proc/sys/net/ipv4/ip_forward &> /dev/null;
+    fi
 }
 
 
 function RESET_FW {
+    # Flush tables
+    $IPTABLES --table filter --flush
+    $IPTABLES --table mangle --flush
+    $IPTABLES --table nat --flush
+    $IPTABLES --table raw --flush
 
-	# Flush tables
-	$IPTABLES --table filter --flush
-	$IPTABLES --table mangle --flush
-	$IPTABLES --table nat --flush
-	$IPTABLES --table raw --flush
+    $IP6TABLES --table filter --flush
+    $IP6TABLES --table mangle --flush
+    $IP6TABLES --table raw --flush
 
-	$IP6TABLES --table filter --flush
-	$IP6TABLES --table mangle --flush
-	$IP6TABLES --table raw --flush
-
-
-	# Delete user chains
-	$IPTABLES --table filter --delete-chain
-	$IP6TABLES --table filter --delete-chain
-
+    # Delete user chains
+    $IPTABLES --table filter --delete-chain
+    $IP6TABLES --table filter --delete-chain
 }
 
 # "DROP" mode
 function MODE_DROP {
-	$IPTABLES --table filter --policy INPUT DROP
-	$IPTABLES --table filter --policy FORWARD DROP
+    $IPTABLES --table filter --policy INPUT DROP
+    $IPTABLES --table filter --policy FORWARD DROP
 
-	$IP6TABLES --table filter --policy INPUT DROP
+    $IP6TABLES --table filter --policy INPUT DROP
 
-        # policy drop is buggy, add a drop rule instead
-	#$IP6TABLES --table filter --policy FORWARD DROP 
-        $IP6TABLES --table filter --append FORWARD --jump DROP
+    # policy drop is buggy, add a drop rule instead
+    $IP6TABLES --table filter --policy FORWARD DROP 
+    #$IP6TABLES --table filter --append FORWARD --jump DROP
 }
 
 # "ACCEPT" mode
 function MODE_ACCEPT {
-	$IPTABLES --table filter --policy INPUT ACCEPT
-	$IPTABLES --table filter --policy FORWARD ACCEPT
+    $IPTABLES --table filter --policy INPUT ACCEPT
+    $IPTABLES --table filter --policy FORWARD ACCEPT
 
-	$IP6TABLES --table filter --policy INPUT ACCEPT
-	$IP6TABLES --table filter --policy FORWARD ACCEPT
+    $IP6TABLES --table filter --policy INPUT ACCEPT
+    $IP6TABLES --table filter --policy FORWARD ACCEPT
 }
 
 function DO_START {
-	RESET_FW
-	INIT_FW
-	APPLY_HYPERVISOR_RULES
-	APPLY_BRIDGED_VM_RULES
-	APPLY_VM_COMMON_RULES
-	MODE_DROP
+    RESET_FW
+    INIT_FW
+    APPLY_HYPERVISOR_RULES
+    APPLY_BRIDGED_VM_RULES
+    APPLY_VM_COMMON_RULES
+    MODE_DROP
 }
 
 function DO_STOP {
-	MODE_ACCEPT
-	RESET_FW
+    MODE_ACCEPT
+    RESET_FW
 }
 
 function SHOW_RULES {
